title: Alberto Moyano
description: Editor desde hace más de 30 años, especializado en textos académicos.
logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

