baseURL = 'https://albertomoyano.github.io/albertomoyano/'
languageCode = 'es-es'
title = 'Alberto Moyano'
theme = 'hugo-texify2'

# Configuración de taxonomía
[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

# Menú de navegación
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "Categorías"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Etiquetas"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "Acerca de"
    url = "/about/"
    weight = 40

[params]
  # Color scheme
  color = 'auto' # auto, light o dark
  
  # Descripción para metadatos
  description = "Blog personal de Alberto Moyano"
  
  # Fuente personzalizada - puedes cambiar la familia de fuentes
  # Los valores válidos son 'serif' (por defecto), 'sans' o 'mono'
  fontFamily = "serif"
  
  # Tamaño de fuente personalizado
  fontSize = "1em"
  
  # Archivos CSS personalizados (rutas relativas a 'static/css/')
  customCSS = ["custom.css"]
  
  # Archivos JS personalizados (rutas relativas a 'static/js/')
  customJS = ["custom.js"]
  
  # Formato de fecha
  dateFormat = "2006-01-02"
  
  # Mostrar hora de lectura
  readingTime = true
  
  # Mostrar información de palabras por post
  wordCount = true
  
  # Configuración para mostrar la última modificación
  lastMod = true
  
  # Resaltado de sintaxis
  highlight = true
  highlightStyle = "github"
  highlightLanguages = ["python", "javascript", "bash", "css", "html"]
  
  # Configuración de comentarios - puedes habilitar Disqus
  # [params.comments]
  #   enable = true
  #   disqus = "tu-nombre-de-usuario-disqus"

  # Configuración del autor
  [params.author]
    name = "Alberto Moyano"
    email = "alberto.alejandro.moyano@gmail.com" # Opcional
    about = "Breve descripción sobre ti" # Opcional
  
  # Configuración de enlaces sociales
  [params.social]
    github = "albertomoyano"
    # twitter = "tu_usuario_twitter"
    linkedin = "edicion-cientifica/"
    email = "alberto.alejandro.moyano@gmail.com"
    stackoverflow = "alberto-moyano"
    # facebook = ""
    # instagram = ""
    # youtube = ""
  
  # Configuración de texto de la página principal
  [params.homeText]
    title = "¡Bienvenido a mi blog!"
    content = "Aquí encontrarás artículos sobre mis intereses y proyectos."
  
  # Configuración para matemáticas y LaTeX
  [params.katex]
    enable = true
    mathDelimiters = true
  
  # Configuración para el pie de página
  [params.footer]
    since = 2019  # Año de inicio del sitio
    license = "CC BY-NC-SA 4.0"  # Tipo de licencia
    licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0"
    
  # Habilitar la tabla de contenidos para los posts
  [params.toc]
    enable = true  # true o false
    tocMaxDepth = 4  # Profundidad máxima de encabezados en la ToC